
#--------------------------Server--------------------------
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088
  servlet:
    context-path: /
    session:
      timeout: 1800 # Session timeout. If a duration suffix is not specified, seconds will be used.

#  ssl:
#    key-store: classpath:SHA256withRSA_wx.ccepc.com.pfx
#    key-store-type: JKS
#    key-store-password: 1234
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.btten.dao

spring:
  #--------------------------charset--------------------------
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  quartz:
    job-store-type: memory

  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #热部署生效

  redis:
    flush-mode: on_save
    namespace: spring:blog # Namespace for keys used to store sessions.
    repositories:
      enabled: false
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 500
    jedis:
      pool:
        max-active: 40
        max-idle: 10
        max-wait: 1
        min-idle: 5
  #测试环境mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/itsblog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: devjava
    password: ccepcadmin
    platform: mysql
    hikari:
      maxLifetime: 60000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 18 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      idle-timeout: 5000
      initialization-fail-timeout: 3000
      minimum-idle: 1
      connection-timeout: 10000
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
